name: workflow_dispatch-workflow
on:
  workflow_dispatch:

jobs:
  workflow_dispatch-job:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo hello world
    - name: step2
      run: |
        echo hello world
        echo github action